import type { Roster, Unit } from '../../../packages/shared/src/types'
import { generateId } from '../../../packages/shared/src/utils'

export const MOCK_UNITS: Unit[] = [
  {
    id: generateId(),
    name: 'Intercessor Squad',
    points: 160,
    count: 10,
    movement: '6"',
    toughness: 4,
    save: '3+',
    wounds: 2,
    leadership: 6,
    objectiveControl: 2,
    currentWounds: 10,
    notes: 'Troops choice. Objective Secured.',
    abilities: ['Oath of Moment', 'Objective Secured'],
    weapons: [
      { name: 'Bolt Rifle', range: '30"', attacks: '2', skill: '3+', strength: 4, ap: -1, damage: '1', type: 'ranged' },
      { name: 'Bolt Pistol', range: '12"', attacks: '1', skill: '3+', strength: 4, ap: 0, damage: '1', type: 'ranged' },
      { name: 'Close Combat Weapon', range: 'Melee', attacks: '3', skill: '3+', strength: 4, ap: 0, damage: '1', type: 'melee' },
    ],
  },
  {
    id: generateId(),
    name: 'Redemptor Dreadnought',
    points: 210,
    count: 1,
    movement: '8"',
    toughness: 10,
    save: '2+',
    wounds: 12,
    leadership: 6,
    objectiveControl: 4,
    currentWounds: 1,
    notes: 'Heavy fire support. Duty Eternal reduces incoming damage.',
    abilities: ['Duty Eternal', 'Oath of Moment'],
    weapons: [
      { name: 'Macro Plasma Incinerator', range: '36"', attacks: 'D6+1', skill: '3+', strength: 9, ap: -3, damage: '2', type: 'ranged' },
      { name: 'Onslaught Gatling Cannon', range: '24"', attacks: '8', skill: '3+', strength: 5, ap: 0, damage: '1', type: 'ranged' },
      { name: 'Redemptor Fist', range: 'Melee', attacks: '5', skill: '3+', strength: 12, ap: -2, damage: '3', type: 'melee' },
    ],
  },
  {
    id: generateId(),
    name: 'Captain in Terminator Armour',
    points: 100,
    count: 1,
    movement: '5"',
    toughness: 5,
    save: '2+',
    wounds: 6,
    leadership: 5,
    objectiveControl: 1,
    currentWounds: 1,
    notes: 'HQ. Provides re-roll aura.',
    abilities: ['Rites of Battle', 'Oath of Moment', 'Leader'],
    weapons: [
      { name: 'Storm Bolter', range: '24"', attacks: '2', skill: '2+', strength: 4, ap: 0, damage: '1', type: 'ranged' },
      { name: 'Relic Weapon', range: 'Melee', attacks: '6', skill: '2+', strength: 5, ap: -2, damage: '2', type: 'melee' },
    ],
  },
  {
    id: generateId(),
    name: 'Eliminators',
    points: 85,
    count: 3,
    movement: '6"',
    toughness: 4,
    save: '3+',
    wounds: 2,
    leadership: 6,
    objectiveControl: 1,
    currentWounds: 3,
    notes: 'Phobos. Precision snipers.',
    abilities: ['Guerrilla Tactics', 'Oath of Moment'],
    weapons: [
      { name: 'Las Fusil', range: '36"', attacks: '1', skill: '3+', strength: 9, ap: -3, damage: 'D6', type: 'ranged' },
      { name: 'Bolt Pistol', range: '12"', attacks: '1', skill: '3+', strength: 4, ap: 0, damage: '1', type: 'ranged' },
      { name: 'Close Combat Weapon', range: 'Melee', attacks: '2', skill: '3+', strength: 4, ap: 0, damage: '1', type: 'melee' },
    ],
  },
]

export const MOCK_ROSTER: Roster = {
  id: 'demo-roster-1',
  name: 'Ultramarines Strike Force',
  faction: 'Adeptus Astartes',
  detachment: 'Gladius Task Force',
  totalPoints: 555,
  maxPoints: 2000,
  units: MOCK_UNITS,
  createdAt: new Date('2026-05-01'),
  updatedAt: new Date('2026-05-10'),
}

export const MOCK_ROSTERS: Roster[] = [
  MOCK_ROSTER,
  {
    id: 'demo-roster-2',
    name: 'Iron Hands Armoured Spearhead',
    faction: 'Adeptus Astartes',
    detachment: 'Ironstorm Spearhead',
    totalPoints: 320,
    maxPoints: 1000,
    units: [],
    createdAt: new Date('2026-04-20'),
    updatedAt: new Date('2026-04-25'),
  },
]